#!/bin/bash  
  
#processname:flower_interact        
#description:celery monitor web portal 
#chkconfig: 2345 20 81  

APP=interact
REDIS_IP=192.168.100.3
REDIS_PORT=6379
REDIS_PASSWD=fhcloud86
DB=1
WEB_PORT=5555

ROOT_PATH=/opt/virt/$APP   
PID_FILE=/var/run/flower_${APP}.pid  
  
. /etc/rc.d/init.d/functions  
  
stop()  
{  
       echo "Stoping $APP flower ..."  
       ps aux | grep $ROOT_PATH/bin/celery | kill -9 `awk '{print $2}'` >/dev/null 2>&1  
       rm -f $PID_FILE  
       usleep 100  
       echo "Shutting down $APP flower: [  OK  ]"      
}  
  
start()  
{  
       echo "Starting $DESC ..."  
       . $ROOT_PATH/bin/activate
       cd $ROOT_PATH/$APP
       celery flower -A $APP --broker=redis://:${REDIS_PASSWD}@${REDIS_IP}:${REDIS_PORT}/${DB} --port=${WEB_PORT} > /dev/null &
       touch $PID_FILE
       ps aux | grep $ROOT_PATH/bin/celery | echo `awk '{print $2}'` > $PID_FILE
       usleep 100  
       echo "Starting $DESC: [  OK  ]"          
}  
  
restart()  
{  
    stop  
    start  
}  
  
case "$1" in  
    start)  
        start  
        ;;  
    stop)  
        stop  
        ;;  
    restart)  
        restart  
        ;;  
    *)  
        echo "Usage: service SERVICE_NAME {start|stop|restart}"  
        exit 1  
esac  
  
exit $?  

